using System;
using System.ComponentModel;
using System.IO;
using System.Threading;
using Spectre.Console;
using Spectre.Console.Cli;

namespace DataSeed.Cli.Commands;

public class InitSettings : GlobalCommandSettings
{
    [CommandArgument(0, "<schema-name>")]
    [Description("Name of the schema to scaffold (without .yaml extension)")]
    public string SchemaName { get; set; } = string.Empty;
}

public class InitCommand : Command<InitSettings>
{
    protected override int Execute(CommandContext context, InitSettings settings, CancellationToken cancellationToken = default)
    {
        var fileName = settings.SchemaName.EndsWith(".yaml", StringComparison.OrdinalIgnoreCase)
            ? settings.SchemaName
            : settings.SchemaName + ".yaml";

        if (File.Exists(fileName))
        {
            if (settings.Format == "json")
                Console.WriteLine("""{"success":false,"error":"File already exists."}""");
            else
                AnsiConsole.MarkupLine($"[red]Error:[/] {fileName} already exists. Delete it first.");
            return 1;
        }

        File.WriteAllText(fileName, GetTemplate(settings.SchemaName));

        if (!settings.Quiet)
        {
            if (settings.Format == "json")
                Console.WriteLine($$$"""{"success":true,"file":"{{{fileName}}}"}""");
            else
                AnsiConsole.MarkupLine($"[green]Created[/] {fileName}");
        }

        return 0;
    }

    private static string GetTemplate(string name) => $$"""
# DataSeed schema — {{name}}
# Run: dataseed validate {{name}}.yaml
#      dataseed plan    {{name}}.yaml --provider claude-code
#      dataseed run     {{name}}.yaml

domain: {{name}}
description: >
  Describe your domain here. This text is sent to the LLM as context
  for all generation calls, so be specific about industry, naming
  conventions, and the purpose of the data.

entities:

  # ── Reference entity ───────────────────────────────────────────────────
  # Small finite set generated entirely by the LLM and stored in the plan.
  - name: Supplier
    type: reference
    count: 10
    description: Manufacturer or brand supplying products
    properties:
      - name: name
        description: Full trade name of the supplier
        examples:
          - Acme Corporation
          - Global Supply Co.
      - name: code
        description: 2-4 character uppercase abbreviation
        hints:
          - unique
        examples:
          - ACM
          - GSC

  # ── Taxonomy entity ─────────────────────────────────────────────────────
  # Hierarchical tree generated by the LLM; leaf paths used as category refs.
  - name: ProductCategory
    type: taxonomy
    depth: 3
    separator: " > "
    description: >
      Hierarchical classification of products. Build a coherent tree
      with top-level trade categories.
    mustInclude:
      - Electronics > Computers > Laptops
      - Electronics > Computers > Desktops

  # ── Dynamic entity ───────────────────────────────────────────────────────
  # Large record set generated by Bogus using the plan strategies.
  - name: Product
    type: dynamic
    count: 500
    description: Product with intentionally varying data quality
    qualityProfile:
      gold: 60%           # full data, good descriptions
      poorDescription: 30% # description degraded or vague
      missingSupplier: 10%  # supplierId absent
    properties:
      - name: sku
        description: Unique product identifier
        hints:
          - unique
          - derived: "{supplier.code}-{sequence:5}"
      - name: description
        description: Product description, quality intentionally varies
        hints:
          - degradable: 30%
      - name: supplierId
        ref: Supplier
        hints:
          - nullable: 10%
          - distribution: long-tail
          - skew: 0.7
      - name: categoryPath
        ref: ProductCategory
        hints:
          - depth: leaf
          - distribution: weighted
      - name: listPrice
        description: List price in USD
        hints:
          - range: 10-5000
          - nullable: 10%
      - name: uom
        description: Unit of measure
        hints:
          - values: [EA, FT, PK, CS]

  # ── Child entity (parent-child) ──────────────────────────────────────────
  # Count is driven by parent; linesPerParent controls cardinality.
  - name: OrderLine
    type: dynamic
    parent: Order
    description: Line item on an order
    hints:
      - linesPerParent: 1-8
    properties:
      - name: productId
        ref: Product
        hints:
          - distribution: long-tail
          - skew: 0.75
      - name: quantity
        description: Quantity ordered
        hints:
          - range: 1-50
      - name: unitPrice
        description: Price charged per unit
        hints:
          - range: 10-5000

  # ── Temporal hints ────────────────────────────────────────────────────────
  - name: Order
    type: dynamic
    count: 200
    description: Customer order
    hints:
      - dateRange: "2023-01-01/2024-12-31"
    properties:
      - name: orderNumber
        description: Order number
        hints:
          - unique
          - derived: "ORD-{sequence:6}"
      - name: orderDate
        description: Date of the order
      - name: customerId
        ref: Customer
        hints:
          - distribution: long-tail
          - skew: 0.6

  - name: Customer
    type: dynamic
    count: 50
    description: Customer account
    properties:
      - name: name
        description: Company name
      - name: accountNumber
        description: Account number
        hints:
          - unique
          - derived: "ACCT-{sequence:4}"
""";
}
